/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JSpinner;
import javax.swing.JTextField;

/**
 *
 * @author Jesus
 */
public class VContrato extends javax.swing.JFrame {

    /**
     * Creates new form VContrato
     */
    public VContrato() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../Imagenes/proyectimage.jpg")).getImage());

    }
    
    public void AgregarListener(ActionListener accion){
        btnBuscar.addActionListener(accion);
        btnSalir.addActionListener(accion);
        btnCrearContrato.addActionListener(accion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVContrato = new javax.swing.JPanel();
        lblContrato = new javax.swing.JLabel();
        lblClente = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        lblTipoCliente = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        lblViglantes = new javax.swing.JLabel();
        jcbBicicletas = new javax.swing.JCheckBox();
        jcbRadios = new javax.swing.JCheckBox();
        spnVigilantes = new javax.swing.JSpinner();
        spnBicicletas = new javax.swing.JSpinner();
        spnRadios = new javax.swing.JSpinner();
        btnBuscar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnCrearContrato = new javax.swing.JButton();

        pnlVContrato.setPreferredSize(new java.awt.Dimension(500, 500));
        pnlVContrato.setLayout(null);

        lblContrato.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblContrato.setText("Contrato");
        pnlVContrato.add(lblContrato);
        lblContrato.setBounds(200, 20, 100, 30);

        lblClente.setText("Cliente");
        pnlVContrato.add(lblClente);
        lblClente.setBounds(100, 90, 33, 14);

        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });
        pnlVContrato.add(txtCliente);
        txtCliente.setBounds(180, 90, 110, 20);

        lblTipoCliente.setText("Tipo");
        pnlVContrato.add(lblTipoCliente);
        lblTipoCliente.setBounds(100, 140, 30, 14);

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Urbanización", "Edificio", "Tienda", "Otros" }));
        cmbTipo.setEnabled(false);
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });
        pnlVContrato.add(cmbTipo);
        cmbTipo.setBounds(280, 130, 110, 20);

        lblViglantes.setText("Cantidad de Vigilantes Solcitados");
        pnlVContrato.add(lblViglantes);
        lblViglantes.setBounds(110, 220, 160, 20);

        jcbBicicletas.setText("Servicio de Bicicleta");
        jcbBicicletas.setEnabled(false);
        jcbBicicletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbBicicletasActionPerformed(evt);
            }
        });
        pnlVContrato.add(jcbBicicletas);
        jcbBicicletas.setBounds(110, 260, 120, 23);

        jcbRadios.setText("Servicio de Radio");
        jcbRadios.setEnabled(false);
        pnlVContrato.add(jcbRadios);
        jcbRadios.setBounds(110, 300, 110, 23);

        spnVigilantes.setModel(new javax.swing.SpinnerNumberModel(1, 1, 8, 1));
        pnlVContrato.add(spnVigilantes);
        spnVigilantes.setBounds(350, 220, 30, 20);

        spnBicicletas.setModel(new javax.swing.SpinnerNumberModel(1, 1, 8, 1));
        pnlVContrato.add(spnBicicletas);
        spnBicicletas.setBounds(350, 260, 30, 20);

        spnRadios.setModel(new javax.swing.SpinnerNumberModel(1, 1, 8, 1));
        pnlVContrato.add(spnRadios);
        spnRadios.setBounds(350, 300, 30, 20);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        pnlVContrato.add(btnBuscar);
        btnBuscar.setBounds(310, 90, 80, 23);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        pnlVContrato.add(btnSalir);
        btnSalir.setBounds(290, 440, 80, 23);
        pnlVContrato.add(jSeparator1);
        jSeparator1.setBounds(40, 370, 420, 10);
        pnlVContrato.add(jSeparator2);
        jSeparator2.setBounds(40, 170, 420, 10);

        btnCrearContrato.setText("Crear Contrato");
        btnCrearContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearContratoActionPerformed(evt);
            }
        });
        pnlVContrato.add(btnCrearContrato);
        btnCrearContrato.setBounds(120, 440, 130, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVContrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVContrato, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCrearContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearContratoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearContratoActionPerformed

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void jcbBicicletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbBicicletasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbBicicletasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VContrato().setVisible(true);
            }
        });
    }

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    public void setBtnBuscar(JButton btnBuscar) {
        this.btnBuscar = btnBuscar;
    }

    public JButton getBtnSalir() {
        return btnSalir;
    }

    public void setBtnSalir(JButton btnSalir) {
        this.btnSalir = btnSalir;
    }

    public JComboBox<String> getCmbTipo() {
        return cmbTipo;
    }

    public void setCmbTipo(JComboBox<String> cmbTipo) {
        this.cmbTipo = cmbTipo;
    }

    public JCheckBox getJcbBicicletas() {
        return jcbBicicletas;
    }

    public void setJcbBicicletas(JCheckBox jcbBicicletas) {
        this.jcbBicicletas = jcbBicicletas;
    }

    public JCheckBox getJcbRadios() {
        return jcbRadios;
    }

    public void setJcbRadios(JCheckBox jcbRadios) {
        this.jcbRadios = jcbRadios;
    }

    public JSpinner getSpnBicicletas() {
        return spnBicicletas;
    }

    public void setSpnBicicletas(JSpinner spnBicicletas) {
        this.spnBicicletas = spnBicicletas;
    }

    public JSpinner getSpnRadios() {
        return spnRadios;
    }
    
    public JButton getBtnCrearContrato() {
        return btnCrearContrato;
    }

    public void setBtnCrearContrato(JButton btnCrearContrato) {
        this.btnCrearContrato = btnCrearContrato;
    }

    

    public void setSpnRadios(JSpinner spnRadios) {
        this.spnRadios = spnRadios;
    }

    public JSpinner getSpnVigilantes() {
        return spnVigilantes;
    }

    public void setSpnVigilantes(JSpinner spnVigilantes) {
        this.spnVigilantes = spnVigilantes;
    }

    public JTextField getTxtCliente() {
        return txtCliente;
    }

    public void setTxtCliente(JTextField txtCliente) {
        this.txtCliente = txtCliente;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCrearContrato;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JCheckBox jcbBicicletas;
    private javax.swing.JCheckBox jcbRadios;
    private javax.swing.JLabel lblClente;
    private javax.swing.JLabel lblContrato;
    private javax.swing.JLabel lblTipoCliente;
    private javax.swing.JLabel lblViglantes;
    private javax.swing.JPanel pnlVContrato;
    private javax.swing.JSpinner spnBicicletas;
    private javax.swing.JSpinner spnRadios;
    private javax.swing.JSpinner spnVigilantes;
    private javax.swing.JTextField txtCliente;
    // End of variables declaration//GEN-END:variables
}
