/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.event.*;
import javax.swing.JButton;

/**
 *
 * @author Yonnibeth
 */
public class VFactura extends javax.swing.JFrame {

    /**
     * Creates new form VFactura
     */
    public VFactura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFactura = new javax.swing.JPanel();
        lblFactura = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetFact = new javax.swing.JTable();
        cbxClientes = new javax.swing.JComboBox<String>();
        lblCliente = new javax.swing.JLabel();
        lblNroFact = new javax.swing.JLabel();
        lblNro = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        btnFacturar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblTotalCanc = new javax.swing.JLabel();
        lblMontoTotal = new javax.swing.JLabel();
        sepFecha = new javax.swing.JSeparator();
        btnVerificar = new javax.swing.JButton();
        sepFecha1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(580, 480));
        getContentPane().setLayout(null);

        pnlFactura.setPreferredSize(new java.awt.Dimension(550, 450));
        pnlFactura.setLayout(null);

        lblFactura.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblFactura.setText("Factura");
        pnlFactura.add(lblFactura);
        lblFactura.setBounds(60, 30, 150, 30);

        tblDetFact.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDetFact);

        pnlFactura.add(jScrollPane1);
        jScrollPane1.setBounds(40, 160, 500, 190);

        cbxClientes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxClientesActionPerformed(evt);
            }
        });
        pnlFactura.add(cbxClientes);
        cbxClientes.setBounds(410, 40, 100, 20);

        lblCliente.setText("Cliente");
        pnlFactura.add(lblCliente);
        lblCliente.setBounds(360, 40, 60, 20);

        lblNroFact.setText("Numero Factura");
        pnlFactura.add(lblNroFact);
        lblNroFact.setBounds(60, 80, 90, 20);

        lblNro.setText("nro fact");
        pnlFactura.add(lblNro);
        lblNro.setBounds(170, 80, 50, 20);

        lblFecha.setText("Fecha");
        pnlFactura.add(lblFecha);
        lblFecha.setBounds(360, 80, 29, 14);

        btnFacturar.setText("Facturar");
        pnlFactura.add(btnFacturar);
        btnFacturar.setBounds(330, 400, 80, 23);

        btnSalir.setText("Salir");
        pnlFactura.add(btnSalir);
        btnSalir.setBounds(440, 400, 80, 23);

        lblTotalCanc.setText("Total a Cancelar");
        pnlFactura.add(lblTotalCanc);
        lblTotalCanc.setBounds(270, 360, 80, 20);

        lblMontoTotal.setText("monto");
        pnlFactura.add(lblMontoTotal);
        lblMontoTotal.setBounds(380, 360, 70, 20);
        pnlFactura.add(sepFecha);
        sepFecha.setBounds(60, 70, 150, 10);

        btnVerificar.setText("Verificar(tentativo)");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });
        pnlFactura.add(btnVerificar);
        btnVerificar.setBounds(400, 120, 123, 23);
        pnlFactura.add(sepFecha1);
        sepFecha1.setBounds(360, 70, 150, 10);

        getContentPane().add(pnlFactura);
        pnlFactura.setBounds(0, 0, 550, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxClientesActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VFactura().setVisible(true);
            }
        });
    }
    
    public void AgregarListener(ActionListener accion){
        btnVerificar.addActionListener(accion);
    }
    
    public JButton getBtnVerificar(){
        return btnVerificar;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFacturar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JComboBox<String> cbxClientes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblFactura;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblMontoTotal;
    private javax.swing.JLabel lblNro;
    private javax.swing.JLabel lblNroFact;
    private javax.swing.JLabel lblTotalCanc;
    private javax.swing.JPanel pnlFactura;
    private javax.swing.JSeparator sepFecha;
    private javax.swing.JSeparator sepFecha1;
    private javax.swing.JTable tblDetFact;
    // End of variables declaration//GEN-END:variables
}
