/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import java.awt.event.*;
import javax.swing.JTextField;

/**
 *
 * @author Usuario
 */
public class VNomina extends javax.swing.JFrame {

    /**
     * Creates new form VNomina
     */
    public VNomina() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void AgregarListener(ActionListener accion)
    {
        btnCancelar.addActionListener(accion);
        btnConsultaNomina.addActionListener(accion);
    }

    public JButton getBtnSalir() {
        return btnCancelar;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JRadioButton getRbtMensual() {
        return rbtMensual;
    }

    public JRadioButton getRbtSemanal() {
        return rbtSemanal;
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNomina = new javax.swing.JPanel();
        lblNomina = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblSemanal = new javax.swing.JLabel();
        rbtSemanal = new javax.swing.JRadioButton();
        lblMensual = new javax.swing.JLabel();
        rbtMensual = new javax.swing.JRadioButton();
        btnConsultaNomina = new javax.swing.JButton();
        jspNomina = new javax.swing.JScrollPane();
        jtlNomina = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtIdVig = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlNomina.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNomina.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNomina.setText("Nomina");
        pnlNomina.add(lblNomina, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 100, -1));

        lblTipo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblTipo.setText("Tipo De Periodo");
        pnlNomina.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        lblSemanal.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblSemanal.setText("Semanal");
        pnlNomina.add(lblSemanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));
        pnlNomina.add(rbtSemanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, 20));

        lblMensual.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblMensual.setText("Mensual");
        pnlNomina.add(lblMensual, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));
        pnlNomina.add(rbtMensual, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, 20));

        btnConsultaNomina.setText("Consultar");
        pnlNomina.add(btnConsultaNomina, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        jtlNomina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Vigilante", "Monto Horas", "Monto Horas Extras", "Total a Pagar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jspNomina.setViewportView(jtlNomina);

        pnlNomina.add(jspNomina, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 590, 160));

        btnCancelar.setText("Cancelar");
        pnlNomina.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 80, -1));

        btnSalir.setText("Salir");
        pnlNomina.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 80, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Vigilante");
        pnlNomina.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 50, -1));

        txtIdVig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdVigActionPerformed(evt);
            }
        });
        pnlNomina.add(txtIdVig, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 636, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(pnlNomina, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(pnlNomina, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdVigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdVigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdVigActionPerformed

    public JButton getBtnConsultaNomina() {
        return btnConsultaNomina;
    }

    public JTable getJtlNomina() {
        return jtlNomina;
    }

    public JTextField getTxtIdVig() {
        return txtIdVig;
    }

    public JRadioButton getjRadioButton3() {
        return rbtSemanal;
    }

    public JRadioButton getjRadioButton4() {
        return rbtMensual;
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VNomina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsultaNomina;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jspNomina;
    private javax.swing.JTable jtlNomina;
    private javax.swing.JLabel lblMensual;
    private javax.swing.JLabel lblNomina;
    private javax.swing.JLabel lblSemanal;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JPanel pnlNomina;
    private javax.swing.JRadioButton rbtMensual;
    private javax.swing.JRadioButton rbtSemanal;
    private javax.swing.JTextField txtIdVig;
    // End of variables declaration//GEN-END:variables
}
