/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import java.awt.event.*;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;
//import java.awt.event.ActionListener;

/**
 *
 * @author Yonnibeth
 */
public class VVigilante extends javax.swing.JFrame {

    /**
     * Creates new form VVigilante
     */
    public VVigilante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVigilantes = new javax.swing.JPanel();
        lblCedula = new javax.swing.JLabel();
        lblVigilantes = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jbtBuscar = new javax.swing.JButton();
        txtDireccion = new javax.swing.JTextField();
        jbtModificar = new javax.swing.JButton();
        jbtEliminar = new javax.swing.JButton();
        lblTelf = new javax.swing.JLabel();
        txtTelf = new javax.swing.JTextField();
        jbtSalir = new javax.swing.JButton();

        setName("frmVigilantes"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlVigilantes.setPreferredSize(new java.awt.Dimension(450, 460));
        pnlVigilantes.setLayout(null);

        lblCedula.setText("Cedula");
        pnlVigilantes.add(lblCedula);
        lblCedula.setBounds(60, 190, 90, 20);

        lblVigilantes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblVigilantes.setText("Vigilantes");
        pnlVigilantes.add(lblVigilantes);
        lblVigilantes.setBounds(60, 10, 150, 50);

        lblCodigo.setText("Código");
        pnlVigilantes.add(lblCodigo);
        lblCodigo.setBounds(60, 70, 90, 20);

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        pnlVigilantes.add(txtCodigo);
        txtCodigo.setBounds(190, 70, 90, 20);

        lblNombre.setText("Nombre");
        pnlVigilantes.add(lblNombre);
        lblNombre.setBounds(60, 110, 90, 20);
        pnlVigilantes.add(txtNombre);
        txtNombre.setBounds(190, 110, 90, 20);

        lblApellido.setText("Apellido");
        pnlVigilantes.add(lblApellido);
        lblApellido.setBounds(60, 150, 90, 20);
        pnlVigilantes.add(txtApellido);
        txtApellido.setBounds(190, 150, 90, 20);

        lblDireccion.setText("Dirección");
        pnlVigilantes.add(lblDireccion);
        lblDireccion.setBounds(60, 230, 90, 20);
        pnlVigilantes.add(txtCedula);
        txtCedula.setBounds(190, 190, 90, 20);

        jbtBuscar.setText("Buscar");
        jbtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBuscarActionPerformed(evt);
            }
        });
        pnlVigilantes.add(jbtBuscar);
        jbtBuscar.setBounds(330, 70, 80, 30);
        pnlVigilantes.add(txtDireccion);
        txtDireccion.setBounds(190, 230, 90, 20);

        jbtModificar.setText("Modificar");
        jbtModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtModificarActionPerformed(evt);
            }
        });
        pnlVigilantes.add(jbtModificar);
        jbtModificar.setBounds(330, 140, 80, 30);

        jbtEliminar.setText("Eliminar");
        jbtEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEliminarActionPerformed(evt);
            }
        });
        pnlVigilantes.add(jbtEliminar);
        jbtEliminar.setBounds(330, 210, 80, 30);

        lblTelf.setText("Telefono");
        pnlVigilantes.add(lblTelf);
        lblTelf.setBounds(60, 270, 90, 20);
        pnlVigilantes.add(txtTelf);
        txtTelf.setBounds(190, 270, 90, 20);

        jbtSalir.setText("Salir");
        pnlVigilantes.add(jbtSalir);
        jbtSalir.setBounds(330, 300, 80, 30);

        getContentPane().add(pnlVigilantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtModificarActionPerformed

    private void jbtEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtEliminarActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void jbtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VVigilante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VVigilante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VVigilante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VVigilante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VVigilante().setVisible(true);
            }
        });
    }
    public void AgregarListener (ActionListener accion){
        jbtBuscar.addActionListener(accion);
        jbtModificar.addActionListener(accion);
        jbtEliminar.addActionListener(accion);
        jbtSalir.addActionListener(accion);
    }
    
    public JButton getJbtBuscar(){
        return jbtBuscar;
    }
    
    public JButton getJbtModificar(){
        return jbtModificar;
    }
    
    public JButton getjbtEliminar(){
        return jbtEliminar;
    }
    
    public JButton getJbtSalir(){
        return jbtSalir;
    }
    
    public JTextField getTxtCodigo(){
        return txtCodigo;
    }
    
    public JTextField getTxtNombre(){
        return txtNombre;
    }
    
    public JTextField getTxtApellido(){
        return txtApellido;
    }
    
    public JTextField getTxtCedula(){
        return txtCedula;
    }
    
    public JTextField getTxtDireccion(){
        return txtDireccion;
    }
    
    public JTextField getTxtTelf(){
        return txtTelf;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtBuscar;
    private javax.swing.JButton jbtEliminar;
    private javax.swing.JButton jbtModificar;
    private javax.swing.JButton jbtSalir;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelf;
    private javax.swing.JLabel lblVigilantes;
    private javax.swing.JPanel pnlVigilantes;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelf;
    // End of variables declaration//GEN-END:variables
}
